### PR TITLE
Branch1

### PR DESCRIPTION
**Pull request by CaptainTron**
changed the scrollbar design,added new bootstrap CDN, changed some padding to fit good, dynamic background color changer of 'Enable Dark/Light Mode' button according to choice of user.

### CODE REVIEW

**Comment by CaptainTron** [comment]
Thanks for letting me use my skills to help you man!!

**Comment by CaptainTron** [comment]
Is there any problem in my changes @goodchai0 , why didn't you take action to my request.
Let me know if there any problem.

**Comment by goodchai0** [comment]
I have my exams, so Really busy right now. Sorry.

**Comment by goodchai0** [comment]
Star the repo

**Pull request merged**
