### PR TITLE
Created day planner using tailwind css and next js

### PR DESCRIPTION
**Pull request by palhimalaya**
You can just use "npm install" in terminal and then use "npm run dev" to start the next js project

### CODE REVIEW

**Comment by palhimalaya** [comment]
https://github.com/palhimalaya/Day_Planner_Nextjs 

visit this link for the preview of the new modified page

**Comment by palhimalaya** [comment]
https://dayplannerapp.netlify.app/


why merge late?

**Comment by goodchai0** [comment]
This looks awesome. But merging it means changing the whole codebase. I specially made this repo for beginner in html,css,js so they can participate in hacktoberfest. May we do something else with this awesome project? any suggestion.

**Comment by palhimalaya** [comment]
I just redesign the codebase in new folder not affect the original one. i
didn't deleted any other codebase they can use other and those who knows
react tailwind other languages can also contributes  that's the  purpose..
If you think this is Right u can merge.

**Pull request merged**
