### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by VarunVerma307**
hey !
I had added the footer below their is pic attached for your convince
 
fghj

please check it out and merge it...

### CODE REVIEW

**Comment by goodchai0** [comment]
resolve the conflict and please star the repo

**Comment by VarunVerma307** [comment]
Hi!
the conflict has been resolved kindly check it and merge it
sorry for the inconvince..

**Comment by goodchai0** [comment]
Check again.

**Comment by VarunVerma307** [comment]
hello @goodchai0 !

I had resolve the conflict kindly merge it

Capture

**Pull request merged**
